sudo: false
language: cpp
compiler:
  - gcc
  #- clang
os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
   # - gcc-4.8
    - g++-7
   # - clang

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
script:
  - mkdir build
  - cd build
  - cmake -std=gnu++11 -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - ./homeworks/03-strings-loops-functions-dna-test/dna_test -s
